
version: 2
updates:
   # Frontend (React)
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    reviewers:
      - "gouravanirudh05"

  # # GitHub Actions (if using CI/CD)
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
